# ----- PINECONE CONFIG -----
PINECONE_API_KEY: "00f02102-d83f-4d74-b51a-c0e5744ef03a"
PINECONE_INDEX: "chatdoc" # dimensions: 1536, metric: cosine similarity
PINECONE_FILE_NAMESPACE: "chatdocboe"
PINECONE_CHAT_NAMESPACE: "chatdocchat"
PINECONE_ENV: "us-west1-gcp-free"

# ----- SERVER PORT ----
SERVER_PORT: "8300"

# ---- OPENAI CONFIG -----
EMBEDDINGS_MODEL: "text-embedding-ada-002"
GENERATIVE_MODEL: "gpt-3.5-turbo" # use gpt-4 for better results

# ---- SWAGGER -----
DISABLE_SWAGGER: "false"